### PR TITLE
PR to fix deprecation warning

### PR DESCRIPTION
**Pull request by tarponjargon**
Haven't done this before, but I followed the direction from here:

https://discuss.emberjs.com/t/deprecation-warning-for-addons-future-big-problems/14204

### CODE REVIEW

**Comment by luizcarraro** [comment]
This should also fix:
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: project -> ember-screen -> ember-cli-babel

So +1 !

@mitchlloyd please consider this...

**Comment by mitchlloyd** [comment]
For some reason I thought I had commented on this earlier, but it seems I never did :/

@tarponjargon Thank you for this contribution! Looks great except that there are a few committed merge conflicts. Search for `=======` and you should see them.

**Comment by Subtletree** [comment]
@tarponjargon Nice PR! Any chance you're able to remove those merge conflict remnants so we can get this into master?

**Comment by tarponjargon** [comment]
you can trash it - I just ran the codemod against the addon

**Comment by viniciussbs** [comment]
I'm also facing warnings from `ember-screen`.

**Comment by dnstld** [comment]
Any prevision to merge this? Thanks =)

**Comment by raphaelns-developer** [comment]
I'm also waiting for this merge.

**Comment by iurikothe** [comment]
Hi @mitchlloyd, could we have this baby merged soon? thanks!

**Comment by charles** [comment]
I'm waiting for this merge to. Thanks a lot @mitchlloyd

**Comment by mitchlloyd** [comment]
Thanks for letting me know this is a growing concern! Unfortunately this PR can't be merged because it has git conflict markers in it.

@luizcarraro, @viniciussbs, @dnstld, @raphaelns-developer, @iurikothe, @charles, do any of you have the inclination to run the updater against this project and open another PR? If not I may be able to find some time this weekend to do it.

**Comment by mitchlloyd** [comment]
Thanks to @raphaelns-developer for doing the heavy lifting on this one. I published this update to npm as ember-screen 1.0.0. 🎉

**Pull request closed without merging**
